from setuptools import setup, find_packages

setup(
    name="scalping_bot",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "pandas",
        "numpy",
        "pytest",
        "pytest-asyncio",
        "websockets",
        "aiohttp",
        "python-dotenv",
        "ccxt",
        "sqlalchemy",
        "flask",
        "flask-sqlalchemy",
        "flask-login",
        "flask-wtf",
        "email-validator",
        "qrcode",
        "pillow",
        "requests",
        "python-dateutil",
        "pytz",
        "cryptography",
        "bcrypt",
        "pyjwt",
        "websocket-client",
        "aiohttp",
        "asyncio",
        "pytest-cov",
        "black",
        "flake8",
        "mypy",
        "isort",
        "pre-commit"
    ],
    python_requires=">=3.8",
    author="Adam",
    author_email="adam@example.com",
    description="A cryptocurrency trading bot with scalping strategies",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/adamgit1999/scalping_bot_source",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
) 